# Generated by Django 5.1.4 on 2025-02-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sessionlog_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
